function obj = initGPU(obj)
    fields = fieldnames(obj);
    for f=1:numel(fields)
        if ~strcmp('fig', (fields{f})) ...
                && ~strcmp('popup', (fields{f}))...
                && ~strcmp('plt', (fields{f}))...
                && ~strcmp('ax', (fields{f})) ...
                && ~strcmp('edt', (fields{f})) ...
                && ~strcmp('clims_scatt', (fields{f})) ...
                && ~strcmp('reconpart', (fields{f})) ...
                && ~strcmp('reconrange', (fields{f})) ...
                && ~strcmp('rec_cm', (fields{f})) ...
                && ~strcmp('int_cm', (fields{f}))
            %                     if ismember((fields{f}), {'w','w_old','ws','W','WS'}) || islogical(obj.(fields{f}))
            %                         obj.(fields{f}) = gpuArray((obj.(fields{f})));
            %                         continue
            %                     end
            if isfloat(obj.(fields{f})) || islogical(obj.(fields{f}))
                %                                                 disp((fields{f}))
                obj.(fields{f}) = gpuArray((obj.(fields{f})));
            end
            %                     if  islogical(obj.(fields{f}))
            %                         obj.(fields{f}) = gpuArray((obj.(fields{f})));
            %                     end
        end
    end
end